import React from "react";
import Image from "next/image";

import notFoundImg from "@assets/notfound404.png";
import brokenSocket from "@assets/brokenwire.png";

export const metadata = {
  title: "Portfolio | Page Not Found",
  description: "Generated by create next app",
};

const Page404 = () => {
  return (
    <div className="flex bg-blue-950 flex-col items-center py-8 justify-center ">
      <Image className="block pt-32" src={notFoundImg} alt="404" />
      <Image className="block" src={brokenSocket} alt="broken link" />
    </div>
  );
};

export default Page404;
